{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.teamnewpipe",
    "module" : "NewPipeExtractor",
    "version" : "v0.24.6",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "8.12.1"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "11",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "timeago-generator-v0.24.6.jar",
      "url" : "timeago-generator-v0.24.6.jar",
      "size" : 13011,
      "sha512" : "1175f12e5c1343dfc4fe3029f883f57f551d6730a6a4396e428c40e1c494f60a4d7bd9df91fbd8e169f3c75ffc139ed25ce14bf7f44c0b7c1caf0525c0aa1fb0",
      "sha256" : "07ef14ada15ce29d2946b0df632819cf6f1b870784a63c6e211d38badf628d26",
      "sha1" : "b752c8cbb6cfab6896943312e0e38e31e4e8db59",
      "md5" : "84aba2add2ca00f5e3fbb443ddfcfb02"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "11",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "com.github.TeamNewPipe",
      "module" : "nanojson",
      "version" : {
        "requires" : "1d9e1aea9049fc9f85e68b43ba39fe7be1c1f751"
      }
    }, {
      "group" : "com.google.code.findbugs",
      "module" : "jsr305",
      "version" : {
        "requires" : "3.0.2"
      }
    }, {
      "group" : "com.github.teamnewpipe.NewPipeExtractor",
      "module" : "timeago-parser",
      "version" : {
        "requires" : "v0.24.6"
      }
    } ],
    "files" : [ {
      "name" : "timeago-generator-v0.24.6.jar",
      "url" : "timeago-generator-v0.24.6.jar",
      "size" : 13011,
      "sha512" : "1175f12e5c1343dfc4fe3029f883f57f551d6730a6a4396e428c40e1c494f60a4d7bd9df91fbd8e169f3c75ffc139ed25ce14bf7f44c0b7c1caf0525c0aa1fb0",
      "sha256" : "07ef14ada15ce29d2946b0df632819cf6f1b870784a63c6e211d38badf628d26",
      "sha1" : "b752c8cbb6cfab6896943312e0e38e31e4e8db59",
      "md5" : "84aba2add2ca00f5e3fbb443ddfcfb02"
    } ]
  } ]
}