{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.6.1.aar",
          "url": "media3-exoplayer-1.6.1.aar",
          "size": 1526778,
          "sha512": "2b458ef5f0820f76fb9fa2e57052d7d311020dfaf163dcd60f355c87f6e1817bf60e568642785e09bc883ab2fce41be77730beccd3c606ea151ba55b52925cc0",
          "sha256": "5310778771e37b0c26b418de72e1cd04f676125b82db22fb6054343277cf4263",
          "sha1": "fceed77845112571c186d526106e3d7649ad0eba",
          "md5": "5e228265476f3efdded4807619b1102a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.6.1.aar",
          "url": "media3-exoplayer-1.6.1.aar",
          "size": 1526778,
          "sha512": "2b458ef5f0820f76fb9fa2e57052d7d311020dfaf163dcd60f355c87f6e1817bf60e568642785e09bc883ab2fce41be77730beccd3c606ea151ba55b52925cc0",
          "sha256": "5310778771e37b0c26b418de72e1cd04f676125b82db22fb6054343277cf4263",
          "sha1": "fceed77845112571c186d526106e3d7649ad0eba",
          "md5": "5e228265476f3efdded4807619b1102a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.6.1-sources.jar",
          "url": "media3-exoplayer-1.6.1-sources.jar",
          "size": 1104644,
          "sha512": "b2b2bd9cb6164439fe0c5d75222cfbde5626c5d6c4a979c3f45024e35ac31c7d0d2270e4cf9ead60f94c5191f222cab9eee38860de32cf00f4fb7b8d292077a8",
          "sha256": "4b6ffcfec4aa63263087fcaa2976c3bfcd13af0f2f7d83c914a2359480110db7",
          "sha1": "9f73c6f32c9414134357dce7eeca3863b79a910c",
          "md5": "5505629e628f6752276b66314aec7871"
        }
      ]
    }
  ]
}
