{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.6.1.aar",
          "url": "media3-datasource-1.6.1.aar",
          "size": 165765,
          "sha512": "1fb240eccd3b56017169f77ff1185b8fbac8784039b7e47ebf22cb24bc8fd29b882581f47c369cb350ef43877d2d9bd34fad6a5a4181bc7f7d01e09860dc0251",
          "sha256": "440195cd5ebca949f5e9a6a67341471a9b376ea8cccb95d990f126d462390603",
          "sha1": "b3f77e09603904780d0b42345a8b972424ec9cbc",
          "md5": "497c0c9324b9432e61fc8fafaca4f6e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.6.1.aar",
          "url": "media3-datasource-1.6.1.aar",
          "size": 165765,
          "sha512": "1fb240eccd3b56017169f77ff1185b8fbac8784039b7e47ebf22cb24bc8fd29b882581f47c369cb350ef43877d2d9bd34fad6a5a4181bc7f7d01e09860dc0251",
          "sha256": "440195cd5ebca949f5e9a6a67341471a9b376ea8cccb95d990f126d462390603",
          "sha1": "b3f77e09603904780d0b42345a8b972424ec9cbc",
          "md5": "497c0c9324b9432e61fc8fafaca4f6e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-1.6.1-sources.jar",
          "url": "media3-datasource-1.6.1-sources.jar",
          "size": 137419,
          "sha512": "7fd12e8aa041052055783790632792701d9dabd0ba9fdeb084de348b45ce8645a7d97d7f98276b5bcd7a6e837ba6d289664ee018c56f29d6ae53cb8688e17658",
          "sha256": "d62d1d34ade715f5bd0e9c43b8daa224f2fc54b8a9435e5f3e51401372d27613",
          "sha1": "7a4e0709a975c37cc1af0d0d5a601525d48430be",
          "md5": "78aae5ab0ede0c7f808f44140baba5f3"
        }
      ]
    }
  ]
}
