{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-hls",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-hls-1.6.1.aar",
          "url": "media3-exoplayer-hls-1.6.1.aar",
          "size": 192118,
          "sha512": "c696d78f53ef96b61ef66011afb4c08b869c93f2f4b6b88f666981e173e94f9a0c6c84ff4ac334083582a0c776af7b324ea0b39383721e9eec05a2f10060ecf9",
          "sha256": "cea9f827c5216d6e31d542bf39f6d21493a7b76cb0dcea85823a4f06cfa99881",
          "sha1": "7e0a98690fb455f39cb0ff89ec6f421cf74e77e7",
          "md5": "63055842ce32ad1a4ad828774e9e0dc7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-hls-1.6.1.aar",
          "url": "media3-exoplayer-hls-1.6.1.aar",
          "size": 192118,
          "sha512": "c696d78f53ef96b61ef66011afb4c08b869c93f2f4b6b88f666981e173e94f9a0c6c84ff4ac334083582a0c776af7b324ea0b39383721e9eec05a2f10060ecf9",
          "sha256": "cea9f827c5216d6e31d542bf39f6d21493a7b76cb0dcea85823a4f06cfa99881",
          "sha1": "7e0a98690fb455f39cb0ff89ec6f421cf74e77e7",
          "md5": "63055842ce32ad1a4ad828774e9e0dc7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-hls-1.6.1-sources.jar",
          "url": "media3-exoplayer-hls-1.6.1-sources.jar",
          "size": 135079,
          "sha512": "e60bb54277471e4dde0f88e25f5bb4a25b81e86bfcd6d7e906828be55d629b3d9030af966b77f795b97de9683834cc2f5826a5a9de1c361dd96f30850d9a139b",
          "sha256": "08ae783155e8a5000d947c679f99c6c04ac0af839f141b3bc62a6227795a3835",
          "sha1": "182b672f64a67060136796c5ff8e613ae6a7f8eb",
          "md5": "c838c21108480eb27b418420374bcaff"
        }
      ]
    }
  ]
}
