{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.quickjs",
    "module": "quickjs-android",
    "version": "0.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "quickjs-android-0.9.2.aar",
          "url": "quickjs-android-0.9.2.aar",
          "size": 1505720,
          "sha512": "7b093dd29e9766a4e156ffb291408e481ddaf8cf457717cbc67b01cde74e026baa3de498291e4f9d0681f3d36dda8bf87403c58dd9ef3ca18d7988136969ae32",
          "sha256": "b20a0addc8dd091b22f16c730000204030734231678d2b88538be0ac579510e2",
          "sha1": "8f260be396ae6e3fb873c6baa10704c378723c18",
          "md5": "0874187eead4b47ae5b4cff618b1d4ca"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "quickjs-android-0.9.2.aar",
          "url": "quickjs-android-0.9.2.aar",
          "size": 1505720,
          "sha512": "7b093dd29e9766a4e156ffb291408e481ddaf8cf457717cbc67b01cde74e026baa3de498291e4f9d0681f3d36dda8bf87403c58dd9ef3ca18d7988136969ae32",
          "sha256": "b20a0addc8dd091b22f16c730000204030734231678d2b88538be0ac579510e2",
          "sha1": "8f260be396ae6e3fb873c6baa10704c378723c18",
          "md5": "0874187eead4b47ae5b4cff618b1d4ca"
        }
      ]
    }
  ]
}
