{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.acra",
    "module": "acra-toast",
    "version": "5.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.acra",
          "module": "acra-core",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "acra-toast-5.12.0.aar",
          "url": "acra-toast-5.12.0.aar",
          "size": 11347,
          "sha512": "fd6becb1e764cb76243352bca39c22e19166ec8bf75a2d0d894c2e8cc48a12e6e03c708a1c393edd5a8d0ce96b9de8e2efc6947964332d297cb18592c5b8f19c",
          "sha256": "38c9568a0ea0aebfcb29daf95c6a06560f81554033f33bd4387ea60a52d86af2",
          "sha1": "803d79ce07d284c58db1b234d685b40806f88caf",
          "md5": "d6f85cbf3d39e212b36b59a1ab7b5425"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "ch.acra",
          "module": "acra-core",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "acra-toast-5.12.0.aar",
          "url": "acra-toast-5.12.0.aar",
          "size": 11347,
          "sha512": "fd6becb1e764cb76243352bca39c22e19166ec8bf75a2d0d894c2e8cc48a12e6e03c708a1c393edd5a8d0ce96b9de8e2efc6947964332d297cb18592c5b8f19c",
          "sha256": "38c9568a0ea0aebfcb29daf95c6a06560f81554033f33bd4387ea60a52d86af2",
          "sha1": "803d79ce07d284c58db1b234d685b40806f88caf",
          "md5": "d6f85cbf3d39e212b36b59a1ab7b5425"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acra-toast-5.12.0-sources.jar",
          "url": "acra-toast-5.12.0-sources.jar",
          "size": 3182,
          "sha512": "ccf7377e7d58a49e3eaa2a39ffefc390db7bac01f40b8edf12ea64348ae9da4b91bcbda40ca8794fca561be60cc220d5b48cf875c5af41f28f20ea457738ad3d",
          "sha256": "6e76585dbda1e6b91c667190d6bc9e0466367d7860aa37af9cf934a4b51c8c00",
          "sha1": "3cf4e069e870c752cc41bc62f67110f91a8f8577",
          "md5": "486c7cdd7db8aaabb2b1ad8f493fb6ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acra-toast-5.12.0-javadoc.jar",
          "url": "acra-toast-5.12.0-javadoc.jar",
          "size": 279330,
          "sha512": "0c26287d466fc0b5f3898d35357a6f0bea4c6afa902e46059f6a46cdbad2487047f6e266cd5a3f1457430b3fd72a3e527f3981263968ed6ac29d0628aab13dfa",
          "sha256": "09d4e77edda47baadcd424b497fd15f9e6f5f53e98c2530f32d10e996bbcaa6f",
          "sha1": "06c2210881f90668c0cf1a86e44e8f20b6f6debe",
          "md5": "63fb838168819e054f7ac9516203b161"
        }
      ]
    }
  ]
}
