{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.Blatzar",
    "module" : "NiceHttp",
    "version" : "0.4.13",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "7.4.1"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "dependencies" : [ {
      "group" : "org.jsoup",
      "module" : "jsoup",
      "version" : {
        "requires" : "1.17.2"
      }
    }, {
      "group" : "com.squareup.okhttp3",
      "module" : "okhttp",
      "version" : {
        "requires" : "5.0.0-alpha.12"
      }
    }, {
      "group" : "com.squareup.okhttp3",
      "module" : "okhttp-dnsoverhttps",
      "version" : {
        "requires" : "5.0.0-alpha.12"
      }
    } ],
    "files" : [ {
      "name" : "NiceHttp-0.4.13.jar",
      "url" : "NiceHttp-0.4.13.jar",
      "size" : 50302,
      "sha512" : "78c090a84552600c1d807604a78615488673980195c8321ea6018204a32ae1fe13facfb7bcea02f8d93693536865a84ddd3d1376ab784c4d769b66ecd4b1cf44",
      "sha256" : "c087fbcdcb7da488e81eae172739fcdc1a721b84e1d33ac17aa4928d7308fe4c",
      "sha1" : "8c8324aa0f0d4c0fac0c4ca41c99db1f30cdce3e",
      "md5" : "e8b67ef328c4d3904ef9667526141700"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-core",
      "version" : {
        "requires" : "1.7.1"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-jdk8",
      "version" : {
        "requires" : "1.9.22"
      }
    }, {
      "group" : "org.json",
      "module" : "json",
      "version" : {
        "requires" : "20231013"
      }
    }, {
      "group" : "org.jsoup",
      "module" : "jsoup",
      "version" : {
        "requires" : "1.17.2"
      }
    }, {
      "group" : "com.squareup.okhttp3",
      "module" : "okhttp",
      "version" : {
        "requires" : "5.0.0-alpha.12"
      }
    }, {
      "group" : "com.squareup.okhttp3",
      "module" : "okhttp-dnsoverhttps",
      "version" : {
        "requires" : "5.0.0-alpha.12"
      }
    } ],
    "files" : [ {
      "name" : "NiceHttp-0.4.13.jar",
      "url" : "NiceHttp-0.4.13.jar",
      "size" : 50302,
      "sha512" : "78c090a84552600c1d807604a78615488673980195c8321ea6018204a32ae1fe13facfb7bcea02f8d93693536865a84ddd3d1376ab784c4d769b66ecd4b1cf44",
      "sha256" : "c087fbcdcb7da488e81eae172739fcdc1a721b84e1d33ac17aa4928d7308fe4c",
      "sha1" : "8c8324aa0f0d4c0fac0c4ca41c99db1f30cdce3e",
      "md5" : "e8b67ef328c4d3904ef9667526141700"
    } ]
  } ]
}