{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.teamnewpipe",
    "module" : "NewPipeExtractor",
    "version" : "v0.24.6",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "8.12.1"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "11",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "dependencies" : [ {
      "group" : "com.github.teamnewpipe.NewPipeExtractor",
      "module" : "extractor",
      "version" : {
        "requires" : "v0.24.6"
      }
    } ],
    "files" : [ {
      "name" : "NewPipeExtractor-v0.24.6.jar",
      "url" : "NewPipeExtractor-v0.24.6.jar",
      "size" : 261,
      "sha512" : "a7e567fc4b3c19d7819e21ba9b2dbdd7ef63546595f39dfaaec5e7edd0443482500d58e88500e889b95187cd4d562d2122ba696e630531a2ff75364c7d6a1c7d",
      "sha256" : "a90bd941705931e92f38aee8d9a6ec4c43ce78443a70a341bedaf977c2d69fb3",
      "sha1" : "40c3bf114ba91f6e9f1ba2bedb5e5d793a38d3d5",
      "md5" : "79924ef437289ccd3bb29870ac19d589"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "11",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "com.github.teamnewpipe.NewPipeExtractor",
      "module" : "timeago-parser",
      "version" : {
        "requires" : "v0.24.6"
      }
    }, {
      "group" : "com.github.teamnewpipe.NewPipeExtractor",
      "module" : "extractor",
      "version" : {
        "requires" : "v0.24.6"
      }
    } ],
    "files" : [ {
      "name" : "NewPipeExtractor-v0.24.6.jar",
      "url" : "NewPipeExtractor-v0.24.6.jar",
      "size" : 261,
      "sha512" : "a7e567fc4b3c19d7819e21ba9b2dbdd7ef63546595f39dfaaec5e7edd0443482500d58e88500e889b95187cd4d562d2122ba696e630531a2ff75364c7d6a1c7d",
      "sha256" : "a90bd941705931e92f38aee8d9a6ec4c43ce78443a70a341bedaf977c2d69fb3",
      "sha1" : "40c3bf114ba91f6e9f1ba2bedb5e5d793a38d3d5",
      "md5" : "79924ef437289ccd3bb29870ac19d589"
    } ]
  } ]
}