{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource-okhttp",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-okhttp-1.6.1.aar",
          "url": "media3-datasource-okhttp-1.6.1.aar",
          "size": 9779,
          "sha512": "1638c3233676d973477178643c3d9331fc130723e8235428be021c22622b0bd5828184a06442a4a82c8c6b33b0faf6ac453d4ae707c5522081f7beacb3c5b75c",
          "sha256": "75e3bf2517bcf0fc7a3b35a8b8bbaa6d91620fb3afa263bd0127846268f2b54f",
          "sha1": "1435e58af52756e35c9e847e37e72f2dae854bd9",
          "md5": "11b86c0e0985f99e38b659e57e67dbac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-okhttp-1.6.1.aar",
          "url": "media3-datasource-okhttp-1.6.1.aar",
          "size": 9779,
          "sha512": "1638c3233676d973477178643c3d9331fc130723e8235428be021c22622b0bd5828184a06442a4a82c8c6b33b0faf6ac453d4ae707c5522081f7beacb3c5b75c",
          "sha256": "75e3bf2517bcf0fc7a3b35a8b8bbaa6d91620fb3afa263bd0127846268f2b54f",
          "sha1": "1435e58af52756e35c9e847e37e72f2dae854bd9",
          "md5": "11b86c0e0985f99e38b659e57e67dbac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-okhttp-1.6.1-sources.jar",
          "url": "media3-datasource-okhttp-1.6.1-sources.jar",
          "size": 6270,
          "sha512": "986df7128c1318069dd15cca69266f9203df8e232764803901bce5cffc87b2aa48b9f36be7cae639b9ce0a7ebc5afbe4e719b3b633c9db545c7e1dc87ad3da04",
          "sha256": "23ff7f6320b79704c6216a3d7708f779947bdef7d315f715fce4f2ba2ba33af2",
          "sha1": "50b5364f38b40450207c1ec8ecf1a344f282fac9",
          "md5": "ab19505238f7e10675c59665c1ec31fc"
        }
      ]
    }
  ]
}
