{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-cast",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.5.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.6.1.aar",
          "url": "media3-cast-1.6.1.aar",
          "size": 48652,
          "sha512": "b70cd6d5da407ea51eb077f0c2473fed5f5b4502dbd09a0cd384461a23dbf79da7d0a8f2a62a7f59d68e6dc6fb281d6d1585845b3febc09285c4e604865ecb48",
          "sha256": "f9c222c1889c819157783cd0aaf79e323fb1671aa857058b436b1497144aba02",
          "sha1": "5391e1c4f548bffb33660b57955ebcc91dedfc7a",
          "md5": "52954eafa84896ad21ebc9ba15df7488"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.5.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-cast-1.6.1.aar",
          "url": "media3-cast-1.6.1.aar",
          "size": 48652,
          "sha512": "b70cd6d5da407ea51eb077f0c2473fed5f5b4502dbd09a0cd384461a23dbf79da7d0a8f2a62a7f59d68e6dc6fb281d6d1585845b3febc09285c4e604865ecb48",
          "sha256": "f9c222c1889c819157783cd0aaf79e323fb1671aa857058b436b1497144aba02",
          "sha1": "5391e1c4f548bffb33660b57955ebcc91dedfc7a",
          "md5": "52954eafa84896ad21ebc9ba15df7488"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-cast-1.6.1-sources.jar",
          "url": "media3-cast-1.6.1-sources.jar",
          "size": 25735,
          "sha512": "786d53991fe6b4ba91fe72a3c9938cd7456ca9cdca093f7c16f229a5854ce23fee6a3b3e90d659dc4bf22e18e0face2573ddeb117617befecd94d72ea01cb4e5",
          "sha256": "2f05798896f9a3e8dfc4444802239f0b116ba231fc73c2399c8c76314b6694eb",
          "sha1": "4396e27b3cb6748a8f43100bc1e0c3f9866c1ddd",
          "md5": "4e68302989ca5dab463f8b15757fa0b6"
        }
      ]
    }
  ]
}
