{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "8.11.1"
    }
  },
  "component" : {
    "group" : "com.github.anilbeesetti",
    "module" : "nextlib",
    "version" : "0.8.4",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseApiElements-published",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.jvm.environment" : "android",
      "org.gradle.usage" : "java-api",
      "org.jetbrains.kotlin.platform.type" : "androidJvm"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "2.1.0"
      }
    } ],
    "files" : [ {
      "name" : "nextlib-media3ext-0.8.4.aar",
      "url" : "nextlib-media3ext-0.8.4.aar",
      "size" : 10392702,
      "sha512" : "bb307ec07d9fb1ebb1bdfb68c66ffb148e6da4c71173ce6317ff9b857c43cfa972f60c6840ef3935ff32595a9cc15bd97c74800cb439dd11ecc665efe562f3c4",
      "sha256" : "2b8816e3aee8cb573838a50ea80e75d82bd232a42b2b6b082ce157af66ae0b74",
      "sha1" : "c58ce252e192980303dde22cbdc3ba00372ed270",
      "md5" : "99140c039d8935f9e462d53b264d0a7b"
    } ]
  }, {
    "name" : "releaseRuntimeElements-published",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.jvm.environment" : "android",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "androidJvm"
    },
    "dependencies" : [ {
      "group" : "androidx.media3",
      "module" : "media3-exoplayer",
      "version" : {
        "requires" : "1.5.1"
      }
    }, {
      "group" : "com.google.errorprone",
      "module" : "error_prone_annotations",
      "version" : {
        "requires" : "2.36.0"
      }
    }, {
      "group" : "androidx.annotation",
      "module" : "annotation",
      "version" : {
        "requires" : "1.9.1"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "2.1.0"
      }
    } ],
    "files" : [ {
      "name" : "nextlib-media3ext-0.8.4.aar",
      "url" : "nextlib-media3ext-0.8.4.aar",
      "size" : 10392702,
      "sha512" : "bb307ec07d9fb1ebb1bdfb68c66ffb148e6da4c71173ce6317ff9b857c43cfa972f60c6840ef3935ff32595a9cc15bd97c74800cb439dd11ecc665efe562f3c4",
      "sha256" : "2b8816e3aee8cb573838a50ea80e75d82bd232a42b2b6b082ce157af66ae0b74",
      "sha1" : "c58ce252e192980303dde22cbdc3ba00372ed270",
      "md5" : "99140c039d8935f9e462d53b264d0a7b"
    } ]
  }, {
    "name" : "releaseSourcesElements-published",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.jvm.environment" : "android",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "androidJvm"
    },
    "files" : [ {
      "name" : "nextlib-media3ext-0.8.4.jar",
      "url" : "nextlib-media3ext-0.8.4.jar",
      "size" : 28757,
      "sha512" : "8b7bc50fa338ca2fd180c44694e6746d972801e885976f39016871dc2fca32a724b7b0007aea3b965a055b145ad7896a9cc8bfbb5fecff30fd61cb9f22397244",
      "sha256" : "c8c8f05c6cf7f8ead86d2abab54f1f3887bf69c10179bdfc73117f0f50eb9e29",
      "sha1" : "b6e22903cc53d343c04917f207027ba78abe7c84",
      "md5" : "e5f6d528d26da70e5630865a8d319d98"
    } ]
  } ]
}