{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.teamnewpipe",
    "module" : "NewPipeExtractor",
    "version" : "v0.24.6",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "8.12.1"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "11",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "timeago-parser-v0.24.6.jar",
      "url" : "timeago-parser-v0.24.6.jar",
      "size" : 80074,
      "sha512" : "1e7b89b0ceccbe021be25f46c9dc02b1c043aee60a18dcedbc21dcf006c66bda0a98def3f009ae2f99fd75e64cde466ac4ccc9d58d3fb87d80423c5e1766870b",
      "sha256" : "b1679d56cb0bc6ce9884ddb95fc23f7c089c17ca3a08b9b4e87537f17db137a9",
      "sha1" : "62f182154594f9f9052beb5b60c7d59a774877d7",
      "md5" : "db0bc00ca2527eaa6deace0e6caf8e29"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "11",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "com.google.code.findbugs",
      "module" : "jsr305",
      "version" : {
        "requires" : "3.0.2"
      }
    } ],
    "files" : [ {
      "name" : "timeago-parser-v0.24.6.jar",
      "url" : "timeago-parser-v0.24.6.jar",
      "size" : 80074,
      "sha512" : "1e7b89b0ceccbe021be25f46c9dc02b1c043aee60a18dcedbc21dcf006c66bda0a98def3f009ae2f99fd75e64cde466ac4ccc9d58d3fb87d80423c5e1766870b",
      "sha256" : "b1679d56cb0bc6ce9884ddb95fc23f7c089c17ca3a08b9b4e87537f17db137a9",
      "sha1" : "62f182154594f9f9052beb5b60c7d59a774877d7",
      "md5" : "db0bc00ca2527eaa6deace0e6caf8e29"
    } ]
  } ]
}