{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.6.1.aar",
          "url": "media3-ui-1.6.1.aar",
          "size": 427425,
          "sha512": "fb96143b9bf07ff2eb9aff59e5c69a66647c690023f0b40e3708830e84564909c19bb7659b6176618f3b9220ae145a60451d7d69e22a6dac31d375b1513d8ab3",
          "sha256": "f8fb9f6b470fc0583a08b8e5b7e7be461bfc4dfef7dac5689a5148153f121885",
          "sha1": "beae9868f9b1154d35fcb9c43e0460f917f361ce",
          "md5": "70356aeddfec5afb509cbde2f3c69fa1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.6.1.aar",
          "url": "media3-ui-1.6.1.aar",
          "size": 427425,
          "sha512": "fb96143b9bf07ff2eb9aff59e5c69a66647c690023f0b40e3708830e84564909c19bb7659b6176618f3b9220ae145a60451d7d69e22a6dac31d375b1513d8ab3",
          "sha256": "f8fb9f6b470fc0583a08b8e5b7e7be461bfc4dfef7dac5689a5148153f121885",
          "sha1": "beae9868f9b1154d35fcb9c43e0460f917f361ce",
          "md5": "70356aeddfec5afb509cbde2f3c69fa1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-1.6.1-sources.jar",
          "url": "media3-ui-1.6.1-sources.jar",
          "size": 115236,
          "sha512": "98b01f665dfdb6d6a311a93d639cb945b005874f1b683ed4d17b54457b06f72b314d325f1fda648809ef5eed17e59442935fe73c01c8c42554940c9bc9e8b9e2",
          "sha256": "481042779bb65e37a5e9d6d169196afdf9927a2edc5cc05a8cecb0dc035e1ddd",
          "sha1": "04b71ef8b021d905d112eea841b1cf6028187dd6",
          "md5": "66cc0c0ae67602c508c7e7a8e223f7e7"
        }
      ]
    }
  ]
}
