{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-dash",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-dash-1.6.1.aar",
          "url": "media3-exoplayer-dash-1.6.1.aar",
          "size": 142121,
          "sha512": "c80992c3bee22c14c4258c9c2d6959de12dc5c658f1d4bf9693d65859261dad80611e817697f5e15c55989d0418894f5149b774520253ed19d99f231875104ff",
          "sha256": "962681941c66c8bbae5040e1d0c9922200db883cfea4d19fb91ba75c5cd97a60",
          "sha1": "627f98980bd2dca4e0a537770f531fc394a05cf9",
          "md5": "220f1a24ca2f9fe7cdc0755c49640286"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-dash-1.6.1.aar",
          "url": "media3-exoplayer-dash-1.6.1.aar",
          "size": 142121,
          "sha512": "c80992c3bee22c14c4258c9c2d6959de12dc5c658f1d4bf9693d65859261dad80611e817697f5e15c55989d0418894f5149b774520253ed19d99f231875104ff",
          "sha256": "962681941c66c8bbae5040e1d0c9922200db883cfea4d19fb91ba75c5cd97a60",
          "sha1": "627f98980bd2dca4e0a537770f531fc394a05cf9",
          "md5": "220f1a24ca2f9fe7cdc0755c49640286"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-dash-1.6.1-sources.jar",
          "url": "media3-exoplayer-dash-1.6.1-sources.jar",
          "size": 95920,
          "sha512": "c1864ecfd112d0dd665e478c0f1e360c32f27eea9a8210d4d30310126022aa93560330790687e9c71bea707fd2575c9513d68e8c6acabc626bccf0647457ae0f",
          "sha256": "354f33da70099915052a1d320471096813875d0ec04064365f47049b8cf512ba",
          "sha1": "a85462083740957d789622d0acbc08f7744dc98e",
          "md5": "c9793259c9f35364d9d9f847a8eaaf27"
        }
      ]
    }
  ]
}
