{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-kotlin",
    "version": "2.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.13.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-kotlin-2.13.1.jar",
          "url": "jackson-module-kotlin-2.13.1.jar",
          "size": 125852,
          "sha512": "b3195f67455b525c30d984e7e2a82ea42571f83d3852239e0acd275585eab9007f256b47b2adf6482a620bc10236a3942d6e093789830742021041ded87f3cff",
          "sha256": "816d7e1341353c2cebc2bc4b7d02f6db677cb12f60d6e61328bab67f314463fd",
          "sha1": "e8633bb172310b84462ebf586058b3babdbaf4b1",
          "md5": "e05e0603f62aadf9a4971991d47684df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.13.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-kotlin-2.13.1.jar",
          "url": "jackson-module-kotlin-2.13.1.jar",
          "size": 125852,
          "sha512": "b3195f67455b525c30d984e7e2a82ea42571f83d3852239e0acd275585eab9007f256b47b2adf6482a620bc10236a3942d6e093789830742021041ded87f3cff",
          "sha256": "816d7e1341353c2cebc2bc4b7d02f6db677cb12f60d6e61328bab67f314463fd",
          "sha1": "e8633bb172310b84462ebf586058b3babdbaf4b1",
          "md5": "e05e0603f62aadf9a4971991d47684df"
        }
      ]
    }
  ]
}
