{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.mediarouter",
    "module": "mediarouter",
    "version": "1.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter-testing",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "mediarouter is in atomic group androidx.mediarouter"
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.6.0-beta01.aar",
          "url": "mediarouter-1.6.0-beta01.aar",
          "size": 813999,
          "sha512": "3f3d5708cceb79215400a6e1c9e07867368718f491ff5eaf3c0a8d8842aa633e5ca4d1bc0137485163cc7aa6445a245670c01ab73bbe97f233659bd14376849a",
          "sha256": "dfc1a88084a9282f3dbe1ea29f4b813f075b338198de7d17a149f954e7acecd4",
          "sha1": "0a00fb2ffdc237c7718887f7e9f69f6615d0aa84",
          "md5": "808e97de37c4d9cb96cba39bdfa3ca6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter-testing",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "mediarouter is in atomic group androidx.mediarouter"
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.6.0-beta01.aar",
          "url": "mediarouter-1.6.0-beta01.aar",
          "size": 813999,
          "sha512": "3f3d5708cceb79215400a6e1c9e07867368718f491ff5eaf3c0a8d8842aa633e5ca4d1bc0137485163cc7aa6445a245670c01ab73bbe97f233659bd14376849a",
          "sha256": "dfc1a88084a9282f3dbe1ea29f4b813f075b338198de7d17a149f954e7acecd4",
          "sha1": "0a00fb2ffdc237c7718887f7e9f69f6615d0aa84",
          "md5": "808e97de37c4d9cb96cba39bdfa3ca6b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter-testing",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "mediarouter is in atomic group androidx.mediarouter"
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.6.0-beta01-sources.jar",
          "url": "mediarouter-1.6.0-beta01-sources.jar",
          "size": 208781,
          "sha512": "53e22a076c50a9bf0927c8c8b2faed9c71ad7afa0d7b71123bafa00c907f0415a902e7e61acf93fdb802e06edbe332a2036fb41eb07fa034f3403ea64b93ccd3",
          "sha256": "b6fdd87e6baaf8e53071bf335041f86b6e086a823455ee97a5208dd452dd30fb",
          "sha1": "40006d9a64b505ebdd1cb5c1ee718e2177e5b39c",
          "md5": "c423071926568a3638c484fdd1e3b729"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.mediarouter",
          "module": "mediarouter-testing",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "mediarouter is in atomic group androidx.mediarouter"
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.6.0-beta01-versionMetadata.json",
          "url": "mediarouter-1.6.0-beta01-versionMetadata.json",
          "size": 39458,
          "sha512": "968e4f7c8e1b387feca644b87e6e73769532612ebb8f7c1f1c74c7415cbc961ed486410bc1e38c64147710769fd3bdffb2f430d56d60c31d6181b4a15951cd77",
          "sha256": "ccd87560ed87213f678ebf52892e4e625689cf605cf0f12eaf7f8cd8d63ae3d4",
          "sha1": "bb3681161055582eb9217a7bce40eb98c81279fc",
          "md5": "0d179d31e5571574bea04c7998b4c011"
        }
      ]
    }
  ]
}