{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-container",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-container-1.6.1.aar",
          "url": "media3-container-1.6.1.aar",
          "size": 53203,
          "sha512": "3a17cff804cf5fd76aa008449f9f3099b3bef66c895f04db842824cccaf55b8fcb0f7447d04dc1f4a974eacc22ae6683660947bf9d93bd6cb9ba1a780bbe9463",
          "sha256": "6b0b1e38875c2f2ac4efb3dcc02bb03bd031f4fe6763b624a4db66ac34338b36",
          "sha1": "ff2dbd8c7ae3b44542f7f49aba1ba1f3e356f690",
          "md5": "e26601428544ab32421d2a017bd88215"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-container-1.6.1.aar",
          "url": "media3-container-1.6.1.aar",
          "size": 53203,
          "sha512": "3a17cff804cf5fd76aa008449f9f3099b3bef66c895f04db842824cccaf55b8fcb0f7447d04dc1f4a974eacc22ae6683660947bf9d93bd6cb9ba1a780bbe9463",
          "sha256": "6b0b1e38875c2f2ac4efb3dcc02bb03bd031f4fe6763b624a4db66ac34338b36",
          "sha1": "ff2dbd8c7ae3b44542f7f49aba1ba1f3e356f690",
          "md5": "e26601428544ab32421d2a017bd88215"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-container-1.6.1-sources.jar",
          "url": "media3-container-1.6.1-sources.jar",
          "size": 42325,
          "sha512": "b107145737001368c329d184efdd6e25f502be109025df8751cc876ca3fac9c80c05f53c7fcb11eabc26ae67ccd2b10f91ef02e71fa19467b4fca408d8fb9ec8",
          "sha256": "b1a0fd47f7fd6076ae8e4e33bab4a5ffc89a1444ee4a9f136a5940d7948caed4",
          "sha1": "94a75624d7bf21555926cc6fa665e53ec8440b40",
          "md5": "d904790da833e351f825f891c0c64a3c"
        }
      ]
    }
  ]
}
