{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.rubensousa",
    "module": "previewseekbar",
    "version": "3.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "previewseekbar-3.1.1.aar",
          "url": "previewseekbar-3.1.1.aar",
          "size": 21437,
          "sha512": "5830856da1ed1c676e5024c331eaa372d1440371aa5d078d601a2e0e16938b7ea8e037d1de28e1082dc3fb8543a8201a557d8f3dee0222f6cf1b3eb4a36ccc33",
          "sha256": "edda06956f0abbeb0a74e5e55e8d6865e1e8ec4089502fc409527d47c52c1bba",
          "sha1": "d604df433986c23737402e5835b9d08a2f916dc2",
          "md5": "038a420b31d9bb53b9399325984f37d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "previewseekbar-3.1.1.aar",
          "url": "previewseekbar-3.1.1.aar",
          "size": 21437,
          "sha512": "5830856da1ed1c676e5024c331eaa372d1440371aa5d078d601a2e0e16938b7ea8e037d1de28e1082dc3fb8543a8201a557d8f3dee0222f6cf1b3eb4a36ccc33",
          "sha256": "edda06956f0abbeb0a74e5e55e8d6865e1e8ec4089502fc409527d47c52c1bba",
          "sha1": "d604df433986c23737402e5835b9d08a2f916dc2",
          "md5": "038a420b31d9bb53b9399325984f37d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "previewseekbar-3.1.1-sources.jar",
          "url": "previewseekbar-3.1.1-sources.jar",
          "size": 13523,
          "sha512": "3c2c5b0f910d68a684229da6a4b7eaf5228aa3b65df9438989903d175f7fc43c0d46593b192e563951b612f3f3bc6645a2aa6cb765e06fd55d123b9d9c6c2f21",
          "sha256": "0861f8fc1f0e6c05e243dd2fe85b3071824d332926b4881faba52e0b258b90ae",
          "sha1": "5fc2e4df50b89e9cd50c785d5f61887e57eeb997",
          "md5": "cc2091b7acf1625b9284a286c3e3c742"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "previewseekbar-3.1.1-javadoc.jar",
          "url": "previewseekbar-3.1.1-javadoc.jar",
          "size": 346979,
          "sha512": "754a921ac4ab6d58353eb8aa152d2db2e86cf92ac2db4a42cffca7e7f8f0cfabd46a9e162f1a440dedbf21cca74cd5a1f92e9e529d2306caaa45405d2ab308fd",
          "sha256": "fd077dd31d159ba8d06ac4780de6664e94629dbdceb65a8db64a2abbe556a16d",
          "sha1": "340f162f2531f04a8c8a1e989c84486db21a6bf8",
          "md5": "e5fd11fe2ee643a662a7c7703715b5b0"
        }
      ]
    }
  ]
}
