{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.dokka",
    "module": "dokka-gradle-plugin",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "dokka-gradle-plugin-2.0.0.jar",
          "url": "dokka-gradle-plugin-2.0.0.jar",
          "size": 716871,
          "sha512": "bd12498be7faffc455d8c59b1ef3f50fff906805414e5c0af25d6d9a6442bde93890ec24147352e7493f05e17d35c1d32eeab98e309f8651b619584970f77459",
          "sha256": "f6949733bc03c8615f4ddd10a5375d1daab76ffe200b3891aeb552ab0e6e78e4",
          "sha1": "1e12775bf97934383cbb290c2ee6a86c54469d50",
          "md5": "d769a0189139dbc8c9c186e33434cfc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "dokka-gradle-plugin-2.0.0.jar",
          "url": "dokka-gradle-plugin-2.0.0.jar",
          "size": 716871,
          "sha512": "bd12498be7faffc455d8c59b1ef3f50fff906805414e5c0af25d6d9a6442bde93890ec24147352e7493f05e17d35c1d32eeab98e309f8651b619584970f77459",
          "sha256": "f6949733bc03c8615f4ddd10a5375d1daab76ffe200b3891aeb552ab0e6e78e4",
          "sha1": "1e12775bf97934383cbb290c2ee6a86c54469d50",
          "md5": "d769a0189139dbc8c9c186e33434cfc0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokka-gradle-plugin-2.0.0-javadoc.jar",
          "url": "dokka-gradle-plugin-2.0.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokka-gradle-plugin-2.0.0-sources.jar",
          "url": "dokka-gradle-plugin-2.0.0-sources.jar",
          "size": 125928,
          "sha512": "2d7dbf8f9a933a4f1ae2605f9c995079a1a56537b27db881a13e8a82bb3d730e86f998421aa8c1ba55f901b05aaf917bf21d18c46345e5445787bec4b93783ef",
          "sha256": "6be60fbe19631be452ff9781c80d892a0a9ad1d804e4efc03402c532968d9b22",
          "sha1": "2c940f65bab9feee1ea88eb70e6cf64b69312240",
          "md5": "ac76b4c7995d21cff604302946ddf189"
        }
      ]
    }
  ]
}
