{
  "formatVersion": "1.1",
  "component": {
    "url": "../../qrcode-kotlin/4.3.0/qrcode-kotlin-4.3.0.module",
    "group": "io.github.g0dkar",
    "module": "qrcode-kotlin",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "qrcode-kotlin-release.aar",
          "url": "qrcode-kotlin-android-4.3.0.aar",
          "size": 102921,
          "sha512": "7fcf5b7004f9c1f6bbcb4026b8189231b0f063fe779f33e0d943fa62fee3941c9137e70bc773a2e172946516283faac9afa43372a88df122beb97fd0879d44b6",
          "sha256": "8bcc061c9edd4b49c5eb295ecd200019d1252f48c1ce7e7f9be7bfb2bc7b2df2",
          "sha1": "c13029e29ea726268a433ce411a04d6921d98344",
          "md5": "7cddbaf11ed437d312b43990ca3b8a91"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "qrcode-kotlin-release.aar",
          "url": "qrcode-kotlin-android-4.3.0.aar",
          "size": 102921,
          "sha512": "7fcf5b7004f9c1f6bbcb4026b8189231b0f063fe779f33e0d943fa62fee3941c9137e70bc773a2e172946516283faac9afa43372a88df122beb97fd0879d44b6",
          "sha256": "8bcc061c9edd4b49c5eb295ecd200019d1252f48c1ce7e7f9be7bfb2bc7b2df2",
          "sha1": "c13029e29ea726268a433ce411a04d6921d98344",
          "md5": "7cddbaf11ed437d312b43990ca3b8a91"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "qrcode-kotlin-android-4.3.0-sources.jar",
          "url": "qrcode-kotlin-android-4.3.0-sources.jar",
          "size": 38707,
          "sha512": "6483e03cc138c2cdf5e7bd2a2917b0a782eebfc7155d007df91d48bb4cbbb538b9c6c5d171fa6ed883e8486a21f6b79c2f8a9d5c3a1421efb2154d92612ef5e5",
          "sha256": "628ba40779bf9715f3e912ce1f4a3db4dc240b83c5f74d887977a436d2693879",
          "sha1": "58b8a65e17c38bf2dfaef9bb2e1e50de2ebcbaaa",
          "md5": "151587a1feb7aec9d1a0cb7cf8e14b88"
        }
      ]
    }
  ]
}
