{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-1.6.1.aar",
          "url": "media3-decoder-1.6.1.aar",
          "size": 17815,
          "sha512": "be5fd3b44e0395082d3d69bbe6e8cbec3956f846e41d3ca8d855f2e3727527fff8788fdcf264557ebc44d821f4982d524607a7176dc936cb83654329b9f40f26",
          "sha256": "c4bbb24cd4b73ec2f03b748f57d843fae619fb28be8b689a407532a7477c26bf",
          "sha1": "957c63c6c798a818728aa75f0732a60cf8dbdb8f",
          "md5": "2c59e105786466b0907ec89695156b21"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-1.6.1.aar",
          "url": "media3-decoder-1.6.1.aar",
          "size": 17815,
          "sha512": "be5fd3b44e0395082d3d69bbe6e8cbec3956f846e41d3ca8d855f2e3727527fff8788fdcf264557ebc44d821f4982d524607a7176dc936cb83654329b9f40f26",
          "sha256": "c4bbb24cd4b73ec2f03b748f57d843fae619fb28be8b689a407532a7477c26bf",
          "sha1": "957c63c6c798a818728aa75f0732a60cf8dbdb8f",
          "md5": "2c59e105786466b0907ec89695156b21"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-1.6.1-sources.jar",
          "url": "media3-decoder-1.6.1-sources.jar",
          "size": 18801,
          "sha512": "80b52b8d5d776eed58daeb16f060814bc9223fba594baab9a17ff55b4ee2f0b4a25b39cb856abec299ce3ec54ea0278e50c4c9d59287e834222b8a2c6e0aa129",
          "sha256": "a0af9c555d787271c84b4518214d248e33cc55ebf11789ca9d31074f61e9982a",
          "sha1": "7208fb0a4d61a038c3b0d71ae3f8e1c975728a71",
          "md5": "0da7ac07c91150552af913fcc54df487"
        }
      ]
    }
  ]
}
