{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.teamnewpipe",
    "module" : "NewPipeExtractor",
    "version" : "v0.24.6",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "8.12.1"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "11",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "extractor-v0.24.6.jar",
      "url" : "extractor-v0.24.6.jar",
      "size" : 648745,
      "sha512" : "e44ef550070484110d6a3efcbe81c97a328f69f319eea513f408f8aa6f23acc7519f2ac417ce7f662bc5d7e9fea774beb1be6ae47129ff4041bb5c14ae6a4413",
      "sha256" : "e05595314e6ed0843c99d1ebf0554f3c8b2cc0ff4e10663fb630c68ccea47ecf",
      "sha1" : "d17a6bbf649fabea4d6d0e7ad0d7a6d44079aa16",
      "md5" : "7d9476fb32b399b62c2d3a40c8b09456"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "11",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "com.github.teamnewpipe.NewPipeExtractor",
      "module" : "timeago-parser",
      "version" : {
        "requires" : "v0.24.6"
      }
    }, {
      "group" : "com.github.TeamNewPipe",
      "module" : "nanojson",
      "version" : {
        "requires" : "1d9e1aea9049fc9f85e68b43ba39fe7be1c1f751"
      }
    }, {
      "group" : "org.jsoup",
      "module" : "jsoup",
      "version" : {
        "requires" : "1.19.1"
      }
    }, {
      "group" : "com.google.code.findbugs",
      "module" : "jsr305",
      "version" : {
        "requires" : "3.0.2"
      }
    }, {
      "group" : "org.mozilla",
      "module" : "rhino",
      "version" : {
        "requires" : "1.8.0"
      }
    }, {
      "group" : "org.mozilla",
      "module" : "rhino-engine",
      "version" : {
        "requires" : "1.8.0"
      }
    } ],
    "files" : [ {
      "name" : "extractor-v0.24.6.jar",
      "url" : "extractor-v0.24.6.jar",
      "size" : 648745,
      "sha512" : "e44ef550070484110d6a3efcbe81c97a328f69f319eea513f408f8aa6f23acc7519f2ac417ce7f662bc5d7e9fea774beb1be6ae47129ff4041bb5c14ae6a4413",
      "sha256" : "e05595314e6ed0843c99d1ebf0554f3c8b2cc0ff4e10663fb630c68ccea47ecf",
      "sha1" : "d17a6bbf649fabea4d6d0e7ad0d7a6d44079aa16",
      "md5" : "7d9476fb32b399b62c2d3a40c8b09456"
    } ]
  } ]
}