{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.dokka",
    "module": "dokka-core",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "dokka-core-2.0.0.jar",
          "url": "dokka-core-2.0.0.jar",
          "size": 868570,
          "sha512": "eed80521722d69a2ad9aa435478bff5458b28e74266f68d03f0fb86cd2d3063e05e85a27578a918480f2ac68e6ccd322fa9cce29fb8653dd9d994d7bf2ec641d",
          "sha256": "3b022166b7cfe3ddb4d538e76f97bc8c4134677efd6631034e63fd722e1253ee",
          "sha1": "ae7fd20e6c4809cd8ae5352d0f768e03f9a94166",
          "md5": "a69508bc8968caee6ba5c4a57e0c2d0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.7.1"
          },
          "reason": "CVE-2022-42003"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "dokka-core-2.0.0.jar",
          "url": "dokka-core-2.0.0.jar",
          "size": 868570,
          "sha512": "eed80521722d69a2ad9aa435478bff5458b28e74266f68d03f0fb86cd2d3063e05e85a27578a918480f2ac68e6ccd322fa9cce29fb8653dd9d994d7bf2ec641d",
          "sha256": "3b022166b7cfe3ddb4d538e76f97bc8c4134677efd6631034e63fd722e1253ee",
          "sha1": "ae7fd20e6c4809cd8ae5352d0f768e03f9a94166",
          "md5": "a69508bc8968caee6ba5c4a57e0c2d0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokka-core-2.0.0-sources.jar",
          "url": "dokka-core-2.0.0-sources.jar",
          "size": 66758,
          "sha512": "87b499e7e8791401fce7251ec2b2cdccdcabe163522728bafd8e01bd6d56a5511b454c7293c5e110b9164e9f4f93c63eb3f161257f0b730f68f994ef582e35c0",
          "sha256": "729fe7b695eb868dcbeb459c664f116f7c70c30a6c6c7b161b29aa562e73a830",
          "sha1": "ef703996c91673fc35950fe9ad116eac0c27e767",
          "md5": "e7ffe82a3a93710f2c10f04c9fef7922"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokka-core-2.0.0-javadoc.jar",
          "url": "dokka-core-2.0.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
