{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codingfeline.buildkonfig",
    "module": "buildkonfig-gradle-plugin",
    "version": "0.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildkonfig-gradle-plugin-0.15.2.jar",
          "url": "buildkonfig-gradle-plugin-0.15.2.jar",
          "size": 44792,
          "sha512": "416e1a9681a1fbf3a727f611430a2e1e1789b816046f0b4445a1a4adeadd3d923cc822f3d8fa757fefa6446d5436174e2134f06f9c22d94d160c6845bf312889",
          "sha256": "396cf4b78d55dbc283f56df16dc1efe9c00e380e08bca9fee6c853e1182cfbe6",
          "sha1": "cd26042b4fcdd59c0592e83fbb3ff3cc81c765b1",
          "md5": "61eb89d003097f57d034f369ec044cbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.codingfeline.buildkonfig",
          "module": "buildkonfig-compiler",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "buildkonfig-gradle-plugin-0.15.2.jar",
          "url": "buildkonfig-gradle-plugin-0.15.2.jar",
          "size": 44792,
          "sha512": "416e1a9681a1fbf3a727f611430a2e1e1789b816046f0b4445a1a4adeadd3d923cc822f3d8fa757fefa6446d5436174e2134f06f9c22d94d160c6845bf312889",
          "sha256": "396cf4b78d55dbc283f56df16dc1efe9c00e380e08bca9fee6c853e1182cfbe6",
          "sha1": "cd26042b4fcdd59c0592e83fbb3ff3cc81c765b1",
          "md5": "61eb89d003097f57d034f369ec044cbd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "buildkonfig-gradle-plugin-0.15.2-javadoc.jar",
          "url": "buildkonfig-gradle-plugin-0.15.2-javadoc.jar",
          "size": 261,
          "sha512": "da5435bc32b2ebab4b86bf99ab6971c7dc9c7bf4b67e18bc912beb5f9203eda462ea05474d0d4113a621bed2a1e7b60a68c3e36b9fded5598b2c3544f283dbfb",
          "sha256": "feb1a47deced7c40d1c089fc276fe315895fc241f637f080dd5fc43368a967b5",
          "sha1": "bc3818f202075acfea3d5b801c62ffeb5aabbe79",
          "md5": "1d2ced12171649b643c3c3b565a08c68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "buildkonfig-gradle-plugin-0.15.2-sources.jar",
          "url": "buildkonfig-gradle-plugin-0.15.2-sources.jar",
          "size": 8446,
          "sha512": "7fdeb1b92687c375ea21ff1565e1765b0c678a9b3bf768ca6530ca778027ab83ddd5d07a0add968b2454def4164deb7081b150ab2ad71bffaacaf71c4c302e80",
          "sha256": "079ef0259c6ec3ef9f8b9ce9300619b8ea926d9f4ad9cf39917dc768cd805e89",
          "sha1": "e409a4e07bb400e497d1d72b7fbb481a19e41fd7",
          "md5": "cafbbcdc22e3d7ab42e6e57de38ab4f9"
        }
      ]
    }
  ]
}
